import Foundation

/// The three wire protocols the catalog reduces to. Every provider in it
/// speaks one of them; the OpenAI variants (responses, codex, the router
/// gateways) all also accept plain `/chat/completions`, which is the only
/// shape a one-shot text request needs.
enum AIAdapterKind: String, Codable, Hashable {
    case openai, anthropic, gemini

    /// Unknown kinds fall back to OpenAI rather than failing the whole
    /// catalog decode: a new adapter name upstream shouldn't take the
    /// feature offline.
    init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self = AIAdapterKind(rawValue: raw) ?? .openai
    }
}

/// How to keep a model from thinking. Only present for models that reason
/// by default — writing a commit message is not a reasoning problem, and
/// thinking tokens here are pure latency and cost.
struct AIThinkingOff: Codable, Hashable {
    /// The provider's kill switch: `thinking_type`, `enable_thinking` or
    /// `thinking_budget`. Absent when the model can only be turned down.
    var off: String?
    /// Cheapest effort level the model offers, for when it can't be off.
    var effort: String?
}

struct AIModel: Codable, Identifiable, Hashable {
    let id: String
    let name: String
    /// Context window / max output, when the catalog knows them. Shown in
    /// the picker; nothing depends on them.
    var ctx: Int?
    var out: Int?
    var noThink: AIThinkingOff?
}

/// One provider out of `Resources/providers.json`, which is generated by
/// `scripts/sync-providers.py` from dim-agent's catalog. See that script
/// for what gets dropped on the way in.
struct AIProvider: Codable, Identifiable, Hashable {
    struct Auth: Codable, Hashable {
        /// `Authorization` for most, `x-api-key` for Anthropic-shaped ones.
        let header: String
        /// `"Bearer "` or empty.
        let prefix: String
    }

    let id: String
    let name: String
    let adapter: AIAdapterKind
    let auth: Auth
    let baseUrl: String
    var defaultModelId: String?
    var customModels: Bool?
    var models: [AIModel]

    /// The model list has to come from the endpoint itself — Ollama, LM
    /// Studio, and the gateways whose catalogue changes daily.
    var needsModelLookup: Bool { customModels == true || models.isEmpty }
}

enum AIProviderCatalog {
    /// Not in the catalog: anything the user points at by hand. Kept first
    /// in the list so an unlisted endpoint is one click away.
    static let custom = AIProvider(
        id: "custom",
        name: "Custom (OpenAI-compatible)",
        adapter: .openai,
        auth: Auth(header: "Authorization", prefix: "Bearer "),
        baseUrl: "",
        defaultModelId: nil,
        customModels: true,
        models: []
    )

    private typealias Auth = AIProvider.Auth

    private struct File: Codable {
        let updatedAt: String
        let providers: [AIProvider]
    }

    /// 200KB of JSON, decoded once on first use — which is when the
    /// settings window opens or a generation starts, never at launch.
    static let all: [AIProvider] = [custom] + decode()

    static func provider(id: String) -> AIProvider? {
        all.first { $0.id == id }
    }

    private static func decode() -> [AIProvider] {
        guard let url = catalogURL(),
              let data = try? Data(contentsOf: url),
              let file = try? JSONDecoder().decode(File.self, from: data)
        else { return [] }
        return file.providers
    }

    /// Deliberately not `Bundle.module`: for an executable target SwiftPM
    /// generates an accessor that only looks beside the binary, which
    /// inside a .app means `TheGit.app/TheGit_TheGit.bundle` — a spot
    /// nothing may live in without breaking codesign — and whose failure
    /// mode is `fatalError`, not nil. Three layouts to cover instead, and
    /// an empty catalog rather than a crash if none of them match.
    private static func catalogURL() -> URL? {
        // Packaged .app: Contents/Resources, put there by scripts/bundle.sh.
        if let url = Bundle.main.url(forResource: "providers", withExtension: "json") {
            return url
        }
        // SwiftPM's sidecar bundle, named <package>_<target>. Next to the
        // binary under `swift run`, and next to the .xctest bundle — not
        // the test runner — under `swift test`. SwiftPM writes it flat,
        // Xcode writes the same bundle in the macOS layout, so both spots
        // are worth a look or a debug build finds an empty catalog.
        let code = Bundle(for: BundleToken.self).bundleURL
        let directories = [
            Bundle.main.bundleURL,
            code.deletingLastPathComponent(),
        ]
        let layouts = ["providers.json", "Contents/Resources/providers.json"]
        for directory in directories {
            let sidecar = directory.appendingPathComponent("TheGit_TheGit.bundle")
            for layout in layouts {
                let url = sidecar.appendingPathComponent(layout)
                if FileManager.default.fileExists(atPath: url.path) { return url }
            }
        }
        return nil
    }
}

/// Only exists to name the bundle its code was loaded from.
private final class BundleToken {
}
